### ISSUE TITLE
兼容 rxdart ^0.20.0

### ISSUE THREAD

**Issue by VinciShark** [OpenFlutter/flutter_ok_image#5]
Because every version of ok_image depends on rxdart ^0.19.0 and flutter_app depends on rxdart ^0.20.0, ok_image is forbidden.
So, because flutter_app depends on ok_image ^0.1.1, version solving failed.

pub get failed (1)

**Comment by CaiJingLong** [comment]
ok, i will upgrade rxdart version, and it will be released as the next version changes.
