### ISSUE TITLE
add onImageLoaded Callback

### ISSUE THREAD

**Issue by The-Redhat** [OpenFlutter/flutter_ok_image#9]
Hey it would be really cool, if you add a onImageLoaded Callback.

**Comment by CaiJingLong** [comment]
add params #10 
update version to 0.2.2

**Comment by CaiJingLong** [comment]
https://github.com/OpenFlutter/flutter_ok_image/blob/b1e35255da0c55c7740a76cf711f04555f464e9c/example/lib/main.dart#L146
https://github.com/OpenFlutter/flutter_ok_image/blob/b1e35255da0c55c7740a76cf711f04555f464e9c/example/lib/main.dart#L150-L153

You can see from the code snippet above how to use it.

**Comment by The-Redhat** [comment]
Thank you very much !
